### ISSUE TITLE
Enable FA Quickview thumbnails by default

### ISSUE THREAD

**Issue by Offline-User** [yttrian/glyph.kt#55]
In most servers where FA links are posted, people want embeds for them, having them enabled by default will simplify setting up the bot.

**Comment by yttrian** [comment]
They are enabled by default. 

https://github.com/yttrian/glyph.kt/blob/5df1ab7ae1bd8a4389d93eee272890b210da03bd/glyph-shared/src/main/kotlin/config/server/QuickviewConfig.kt#L38

Do you mean thumbnails within the embed? 

https://github.com/yttrian/glyph.kt/blob/5df1ab7ae1bd8a4389d93eee272890b210da03bd/glyph-shared/src/main/kotlin/config/server/QuickviewConfig.kt#L42

**Comment by Offline-User** [comment]
Apologies, yes, I mean thumbnails within the embed!
